name: Build for Windows

on:
  push:
    paths:
      - 'Source/*'
      - '.github/workflows/build.yaml'
  workflow_dispatch:
    inputs:
      tag:
        description: 'which tag to upload to'
        default: ''

jobs:
  build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: install meson and ninja
      run: pip install meson ninja

    - name: download VS headers and patch header location
      shell: bash
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --depth=1
        mkdir Source/vapoursynth
        cp vapoursynth/include/*.h Source/vapoursynth

    - name: setup MS dev commands
      uses: ilammy/msvc-dev-cmd@v1

    - name: Meson setup
      run: meson setup builddir/ -Db_vscrt=mt
      env:
        CXX: clang-cl
        CXXFLAGS: -mavx -mfma -Xclang -ffast-math
      working-directory: Source

    - name: Meson compile
      run: meson compile -C builddir/ -v
      working-directory: Source

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: release-windows-x64
        path: Source/builddir/*.dll

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.tag != ''
      with:
        tag_name: ${{ github.event.inputs.tag }}
        files: Source/builddir/dpid.dll
        fail_on_unmatched_files: true
        generate_release_notes: false
        prerelease: true
